import { fmtDate, formatMinutes } from "../helpers";

export default function SharedDashboardView({ snapshot }) {
  const profile = snapshot?.profile || {};
  const summary = snapshot?.summary || {};
  const subjects = Array.isArray(snapshot?.subjects) ? snapshot.subjects : [];
  const upcoming = Array.isArray(snapshot?.upcoming) ? snapshot.upcoming : [];
  const report = snapshot?.report || { wins: [], risks: [], focus: [] };

  return (
    <div className="auth-root">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Mono:wght@400;500&display=swap');
        * { margin:0; padding:0; box-sizing:border-box; }
        .auth-root { min-height:100vh; min-height:100dvh; background:#080810; background-image:radial-gradient(circle at 18% 18%, rgba(124,106,247,0.22) 0%, transparent 52%), radial-gradient(circle at 82% 82%, rgba(106,247,196,0.16) 0%, transparent 50%); color:#e8e8f0; font-family:'DM Mono',monospace; padding:28px 18px 36px; }
        .share-shell { max-width:980px; margin:0 auto; }
        .share-hero, .share-card { background:rgba(255,255,255,0.08); backdrop-filter:blur(24px) saturate(1.4); -webkit-backdrop-filter:blur(24px) saturate(1.4); border:1px solid rgba(255,255,255,0.12); border-radius:22px; }
        .share-hero { padding:24px; margin-bottom:18px; }
        .share-title { font-family:'Syne',sans-serif; font-size:30px; font-weight:800; margin-bottom:6px; }
        .share-sub { color:#9d9db4; font-size:12px; line-height:1.7; }
        .share-grid { display:grid; grid-template-columns:repeat(auto-fit, minmax(180px, 1fr)); gap:10px; margin-top:18px; }
        .share-stat { background:rgba(255,255,255,0.06); border:1px solid rgba(255,255,255,0.08); border-radius:16px; padding:14px; }
        .share-stat-label { color:#9d9db4; font-size:10px; text-transform:uppercase; letter-spacing:1px; }
        .share-stat-value { font-family:'Syne',sans-serif; font-size:24px; font-weight:700; margin-top:6px; }
        .share-section-title { font-family:'Syne',sans-serif; font-size:18px; font-weight:700; margin:20px 0 10px; }
        .share-card { padding:18px; margin-bottom:12px; }
        .share-subject-grid { display:grid; grid-template-columns:repeat(auto-fit, minmax(210px, 1fr)); gap:10px; }
        .share-subject-name { font-family:'Syne',sans-serif; font-size:15px; font-weight:700; margin-bottom:10px; }
        .share-row { display:flex; justify-content:space-between; gap:12px; padding:5px 0; color:#cfcfe6; font-size:12px; }
        .share-row span:last-child { color:#ffffff; }
        .share-pill-row { display:flex; flex-wrap:wrap; gap:6px; margin-top:10px; }
        .share-pill { padding:4px 8px; border-radius:999px; background:rgba(124,106,247,0.12); color:#dcd6ff; font-size:10px; }
        .share-list { display:flex; flex-direction:column; gap:8px; }
        .share-item { display:flex; justify-content:space-between; gap:12px; padding:10px 0; border-bottom:1px solid rgba(255,255,255,0.06); }
        .share-item:last-child { border-bottom:none; }
        .share-item-title { font-size:13px; color:#ffffff; }
        .share-item-sub { font-size:11px; color:#9d9db4; margin-top:4px; }
        .share-columns { display:grid; grid-template-columns:repeat(auto-fit, minmax(220px, 1fr)); gap:10px; }
        .share-bullet-list { display:flex; flex-direction:column; gap:8px; }
        .share-bullet-item { font-size:12px; line-height:1.6; color:#d6d6ea; padding-left:14px; position:relative; }
        .share-bullet-item::before { content:""; position:absolute; left:0; top:8px; width:6px; height:6px; border-radius:50%; background:#7c6af7; }
        .share-open-app { display:inline-flex; align-items:center; justify-content:center; margin-top:18px; padding:10px 14px; border-radius:12px; background:#7c6af7; color:white; text-decoration:none; font-family:'Syne',sans-serif; font-weight:700; }
      `}</style>

      <div className="share-shell">
        <div className="share-hero">
          <div className="share-title">{profile.name || "Student"}'s Markd dashboard</div>
          <div className="share-sub">
            {profile.school ? `${profile.school} · ` : ""}Read-only parent or teacher view generated by Markd.
          </div>
          <div className="share-grid">
            <div className="share-stat"><div className="share-stat-label">Streak</div><div className="share-stat-value">{summary.streak || 0} days</div></div>
            <div className="share-stat"><div className="share-stat-label">Level</div><div className="share-stat-value">{summary.level || 1}</div></div>
            <div className="share-stat"><div className="share-stat-label">Weekly tasks</div><div className="share-stat-value">{summary.weeklyTasks || 0}</div></div>
            <div className="share-stat"><div className="share-stat-label">Weekly focus</div><div className="share-stat-value">{formatMinutes(summary.weeklyMinutes || 0)}</div></div>
          </div>
          <a className="share-open-app" href={typeof window !== "undefined" ? `${window.location.origin}${window.location.pathname}` : "#"}>Open main app</a>
        </div>

        <div className="share-section-title">Subject overview</div>
        <div className="share-subject-grid">
          {subjects.map(subject => (
            <div key={subject.id} className="share-card">
              <div className="share-subject-name">{subject.name}</div>
              <div className="share-row"><span>Target</span><span>{subject.target}</span></div>
              <div className="share-row"><span>Average</span><span>{subject.avg !== null && subject.avg !== undefined ? `${subject.avg}%` : "—"}</span></div>
              <div className="share-row"><span>Health</span><span>{subject.health}</span></div>
              <div className="share-row"><span>Next exam</span><span>{subject.nextExam ? `${subject.nextExam.name}` : "Not scheduled"}</span></div>
              {subject.topics?.length > 0 && (
                <div className="share-pill-row">
                  {subject.topics.map(topic => <span key={topic.id} className="share-pill">{topic.topic} · {topic.confidence}</span>)}
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="share-section-title">Upcoming items</div>
        <div className="share-card">
          <div className="share-list">
            {upcoming.map(item => (
              <div key={item.id} className="share-item">
                <div>
                  <div className="share-item-title">{item.label}</div>
                  <div className="share-item-sub">{item.subjectName} · {item.kind}</div>
                </div>
                <div className="share-item-sub">{fmtDate(item.date)}</div>
              </div>
            ))}
          </div>
        </div>

        <div className="share-section-title">Weekly report</div>
        <div className="share-columns">
          <div className="share-card"><div className="share-subject-name">Wins</div><div className="share-bullet-list">{(report.wins || []).map((item, index) => <div key={index} className="share-bullet-item">{item}</div>)}</div></div>
          <div className="share-card"><div className="share-subject-name">Risks</div><div className="share-bullet-list">{(report.risks || []).map((item, index) => <div key={index} className="share-bullet-item">{item}</div>)}</div></div>
          <div className="share-card"><div className="share-subject-name">Next focus</div><div className="share-bullet-list">{(report.focus || []).map((item, index) => <div key={index} className="share-bullet-item">{item}</div>)}</div></div>
        </div>
      </div>
    </div>
  );
}
